### ISSUE TITLE
Better-integrated types using revamped ABI

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1722]
Split from #1661 to distinguish this work from what it is blocked on.

- [ ] FlatArray: https://github.com/pgcentralfoundation/pgrx/issues/1481
  - [x] prototype
  - [ ] impl Iterator
  - [ ] Sized mutation API: https://github.com/pgcentralfoundation/pgrx/issues/1642
  - [ ] Unsized mutation API (possibly defer to ExpandedArray?)
  - [ ] finish https://github.com/pgcentralfoundation/pgrx/issues/1118
- [ ] Record (aka PgHeapTupleV2)
  - [ ] prototype
- [ ] `#[derive(CreateCompositeType)]`: https://github.com/pgcentralfoundation/pgrx/issues/1458
  - [ ] prototype
  - [ ] supporting runtime changes to types via https://github.com/pgcentralfoundation/pgrx/issues/1718
- [ ] Revamping Aggregate someways https://github.com/pgcentralfoundation/pgrx/issues/1719
  - Also see https://github.com/pgcentralfoundation/pgrx/issues/1362
